export const car_parts = [
  {
    persian_name: "گلگیر جلو راننده",
    english_name: "Left Front Fender",
    top: 77,
    right: 72,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "LeftFrontFenderPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "LeftFrontFenderColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "LeftFrontFenderChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "گلگیر جلو شاگرد",
    english_name: "Right Front Fender",
    top: 18,
    right: 72,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "RightFrontFenderPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "RightFrontFenderColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "RightFrontFenderChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "گلگیر عقب راننده",
    english_name: "Left Back Fender",
    top: 74,
    right: 26,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "LeftBackFenderPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "LeftBackFenderColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "LeftBackFenderChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "گلگیر عقب شاگرد",
    english_name: "Right Back Fender",
    top: 21,
    right: 26,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "RightBackFenderPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "RightBackFenderColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "RightBackFenderChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "درب جلو راننده",
    english_name: "Left Front Door",
    top: 80,
    right: 56,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "LeftFrontDoorPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "LeftFrontDoorColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "LeftFrontDoorChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "درب جلو شاگرد",
    english_name: "Right Front Door",
    top: 15,
    right: 56,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "RightFrontDoorPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "RightFrontDoorColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "RightFrontDoorChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "درب عقب راننده",
    english_name: "Left Back Door",
    top: 80,
    right: 40,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "LeftBackDoorPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "LeftBackDoorColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "LeftBackDoorChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "درب عقب شاگرد",
    english_name: "Right Back Door",
    top: 15,
    right: 40,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "RightBackDoorPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "RightBackDoorColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "RightBackDoorChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "کاپوت",
    english_name: "Hood",
    top: 47.5,
    right: 77,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "HoodPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "HoodColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "HoodChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "صندوق",
    english_name: "Trunk",
    top: 47.5,
    right: 17,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "TrunkPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "TrunkColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "TrunkChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "سقف",
    english_name: "Roof",
    top: 47.5,
    right: 44,
    options: [
      {
        persian_option: "رنگ جزئی",
        english_option: "Partial Paint",
        input_id: "RoofPartialColored",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "RoofColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "RoofChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "شاسی جلو راننده",
    english_name: "Left Front Chassis",
    top: 33,
    right: 90,
    options: [
      {
        persian_option: "آسیب جزئی",
        english_option: "Minor Damage",
        input_id: "LeftFrontChassisMinorDamaged",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "LeftFrontChassisColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "LeftFrontChassisChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "شاسی جلو شاگرد",
    english_name: "Right Front Chassis",
    top: 62,
    right: 90,
    options: [
      {
        persian_option: "آسیب جزئی",
        english_option: "Minor Damage",
        input_id: "RightFrontChassisMinorDamaged",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "RightFrontChassisColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "RightFrontChassisChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "شاسی عقب راننده",
    english_name: "Left Back Chassis",
    top: 33,
    right: 6.5,
    options: [
      {
        persian_option: "آسیب جزئی",
        english_option: "Minor Damage",
        input_id: "LeftBackChassisMinorDamaged",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "LeftBackChassisColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "LeftBackChassisChanged",
        color: "#F66B34",
      },
    ],
  },
  {
    persian_name: "شاسی عقب شاگرد",
    english_name: "Right Back Chassis",
    top: 62,
    right: 6.5,
    options: [
      {
        persian_option: "آسیب جزئی",
        english_option: "Minor Damage",
        input_id: "RightBackChassisMinorDamaged",
        color: "#608EF2",
      },
      {
        persian_option: "رنگ",
        english_option: "Paint",
        input_id: "RightBackChassisColored",
        color: "#FFC370",
      },
      {
        persian_option: "تعویض",
        english_option: "Replaced",
        input_id: "RightBackChassisChanged",
        color: "#F66B34",
      },
    ],
  },
];
