import "../styles/globals.css";
import Providers from "@/store/provider";
import MainLayout from "@/layouts/MainLayout";
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <Providers>
        <html lang="fa" dir="rtl">
          <body>
            <NextTopLoader
              color={"#000000"}
              height={4}
              crawlSpeed={2000}
              crawl={true}
              initialPosition={0.08}
              showSpinner={false}
              easing="ease"
              speed={2000}
            />
          <MainLayout>{children}</MainLayout>
          </body>
        </html>
      </Providers>
  );
}
