import "../styles/globals.css";
import Providers from "@/store/provider";
import MainLayout from "@/layouts/MainLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <Providers>
        <html lang="fa" dir="rtl">
          <body>
            <MainLayout>{children}</MainLayout>
          </body>
        </html>
      </Providers>
  );
}
