export const INTERNAL_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  MOBILE_REPRESENTATIVES: "/agent-moving-request",
  PERMANENT_REPRESENTATIVES: "/agent-fixed-request",
  SUPPLIER_REPRESENTATIVES: "/supplier-representatives",
  MYVEHICLE: "my-vehicle",
  MYCAR: "my-car",
  MYMOTORCYCLE: "my-motorcycle",
  CREATE: "create",
  EDIT: "/edit",
};

export const API_PATHS = {
  GETOTP: "/get-otp",
  RESENDOTP: "/resend-otp",
  LOGINPASSWord: "/login-password",
  LOGINOTP: "/login-otp",
  CHECKOTP: "/check-otp",
  REGISTER: "/register",
  LOGOUT: "/logout",
  CONTACTUS: "/contact-us",
  AGENTREQUEST: "/agent-request",
  GEOPROVINCES: "/geo/provinces",
  GEOCITIES: "/geo/cities",
  GEOAREAS: "/geo/areas",
  SUPPLIERREQUEST: "/supplier-request",
  BRANDS: "/car-brands",
  MODELS: "/car-models",
  TIPS: "/car-tips",
  YEARS: "/car-years",
  MOTORBRANDS: "/motor-brands",
  MOTORMODELS: "/motor-models",
  MOTORTIPS: "/motor-tips",
  HEAVYCARBRANDS: "/heavy-car-brands",
  HEAVYCARMODELS: "/heavy-car-models",
  HEAVYCARTIPS: "/heavy-car-tips",
  HEAVYCARYEARS: "/heavy-car-years",
  FILE: "/file",
  CARS: "/cars",
  MOTORS: "/motors",
  HEAVYCARS: "/heavy-cars",
  USERPANEL: "/user-panel",
  INSURANCES: "/insurances",
  SLIDERS: "/sliders",
  ADDCAR: "/add-car",
  GETCODECAR: "/get-code-car",
  ADDCARLOGIN: "/add-car-login",
  MAGSINDEX: "/mags/index",
  MAGS: "/mags",
  MAGCATEGORY: "/mag-categories",
  MAGCOMMENTS: "/mag-comments",
  GETPRODUCT: "/get-product",
  DASHBOARDUSERADDRESS: "/user-panel/user-address",
  ADDRESS: "/address",
  COUPONS: "/coupons",
};

export const META_PATHS = {
  BASEURL: "https://ccme.ir",
  MAGS: "/mags",
  PRODUCTS: "/products",
  BATTERIES: "/batteries",
};
