export const INTERNAL_PATHS = {
    HOME: "/",
    LOGIN: "/login",
    MOBILE_REPRESENTATIVES: "/agent-moving-request",
    PERMANENT_REPRESENTATIVES: "/agent-fixed-request",
    SUPPLIER_REPRESENTATIVES: "/supplier-representatives",
    MYVEHICLE: "my-vehicle",
    MYCAR: "my-car",
    MYMOTORCYCLE: "my-motorcycle",
    CREATE: "create",
    EDIT: "/edit",
};

export const API_PATHS = {
    GETOTP: "/get-otp",
    RESENDOTP: "/resend-otp",
    LOGINPASSWord: "/login-password",
    LOGINOTP: "/login-otp",
    CHECKOTP: "/check-otp",
    REGISTER: "/register",
    LOGOUT: "/logout",
    CONTACTUS: "/contact-us",
    AGENTREQUEST: "/agent-request",
    GEOPROVINCES: "/geo/provinces",
    GEOCITIES: "/geo/cities",
    GEOAREAS: "/geo/areas",
    SUPPLIERREQUEST: "/supplier-request",
    BRANDS: "/car-brands",
    MODELS: "/car-models",
    TIPS: "/car-tips",
    YEARS: "/car-years",
    MOTORBRANDS: "/motor-brands",
    MOTORMODELS: "/motor-models",
    MOTORTIPS: "/motor-tips",
    FILE: "/file",
    CARS: "/cars",
    USERPANEL: "/user-panel",
    INSURANCES: "/insurances",
    SLIDERS: "/sliders",
    ADDCAR: "/add-car",
    GETCODECAR: "/get-code-car",
    ADDCARLOGIN: "/add-car-login"
};
